--- 
abstract: Unified cache interface
author: 
  - Jonathan Swartz <swartz@pobox.com>
build_requires: 
  Date::Parse: 0
  Test::Class: 0
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CHI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::UUID: 0
  Digest::JHash: 0
  File::Spec: 0.80
  Hash::MoreUtils: 0
  List::MoreUtils: 0.13
  Module::Load::Conditional: 0
  Mouse: 0.15
  Storable: 0
  Time::Duration: 1.06
  Time::Duration::Parse: 0.03
  perl: 5.6.0
version: 0.2
