---
abstract: 'Unified cache interface'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Date::Parse: 0
  ExtUtils::MakeMaker: 6.42
  Log::Any::Adapter::Dispatch: 0.05
  Test::Class: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::Log::Dispatch: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CHI
no_index:
  directory:
    - inc
    - lib/CHI/Test
    - lib/CHI/t
    - t
    - xt
  package:
    - CHI::Constants
    - CHI::Serializer::Storable
    - CHI::Test
    - CHI::Types
    - CHI::Util
requires:
  Carp::Assert: 0.20
  Data::UUID: 0
  Digest::JHash: 0
  File::Spec: 0.80
  Hash::MoreUtils: 0
  List::MoreUtils: 0.13
  Log::Any: 0.06
  Module::Load::Conditional: 0
  Moose: 0.66
  Storable: 0
  Task::Weaken: 0
  Time::Duration: 1.06
  Time::Duration::Parse: 0.03
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.30
